### ISSUE TITLE
Add feed button props issue

### ISSUE THREAD

**Issue by ScorpIan555** [ScorpIan555/FakeNewsFeed#1]
Not obvious issue with the 'Add Feed' button object, the bound click handler shows up ok in the REact debugger, posibly conflicting wtih something else?

**Comment by ScorpIan555** [comment]
![screenshot from 2017-08-09 16-19-38](https://user-images.githubusercontent.com/21299975/29142128-e5fd8b70-7d1e-11e7-84b7-91040e9ce19d.png)

**Comment by ScorpIan555** [comment]
Including screenshot of YouTube comment troubleshooting conversation with Dan from Turbo360 (video tutorial series): 

![screenshot from 2017-08-11 07-32-56](https://user-images.githubusercontent.com/21299975/29211495-5fa28608-7e67-11e7-9229-14f0379f88bd.png)

**Comment by ScorpIan555** [comment]
![screenshot from 2017-08-11 07-37-02](https://user-images.githubusercontent.com/21299975/29211580-e94c4c54-7e67-11e7-9769-34b1c2a88c41.png)

**Comment by ScorpIan555** [comment]
https://newsfeed-mtcf6i.turbo360-dev.com/dist/images/screenshot.png

![screenshot from 2017-08-11 07-39-12](https://user-images.githubusercontent.com/21299975/29211634-35a64a50-7e68-11e7-8d17-acea788e9014.png)

**Comment by ScorpIan555** [comment]
Screenshot of my most recent build 07:42 EST  08/11/17:

![screenshot from 2017-08-11 07-42-18](https://user-images.githubusercontent.com/21299975/29211717-af40bb8e-7e68-11e7-9bb8-71f8e9077a86.png)

**Comment by ScorpIan555** [comment]
This is an  error I've encountered myself and when cloning Nick's project on my local machine, same error at same point:

![screenshot from 2017-08-11 14-49-16](https://user-images.githubusercontent.com/21299975/29242671-f84754e0-7f5e-11e7-8848-b37fa8b05589.png)

**Comment by ScorpIan555** [comment]
I was able to get through this by getting rid of the id="sidebar" JSX tag, will circle back to try to find ultimate rooot cause.

**Comment by caseytrombley** [comment]
I ran into the same problem. Seems like something in 'main.js' is allowing the form to post, here is the js from main.js (included with the theme)


// Sidebar.
			var $sidebar = $('#sidebar'),
				$sidebar_inner = $sidebar.children('.inner');

			// Inactive by default on <= large.
				skel
					.on('+large', function() {
						$sidebar.addClass('inactive');
					})
					.on('-large !large', function() {
						$sidebar.removeClass('inactive');
					});

			// Hack: Workaround for Chrome/Android scrollbar position bug.
				if (skel.vars.os == 'android'
				&&	skel.vars.browser == 'chrome')
					$('<style>#sidebar .inner::-webkit-scrollbar { display: none; }</style>')
						.appendTo($head);

			// Toggle.
				if (skel.vars.IEVersion > 9) {

					$('<a href="#sidebar" class="toggle">Toggle</a>')
						.appendTo($sidebar)
						.on('click', function(event) {

							// Prevent default.
								event.preventDefault();
								event.stopPropagation();

							// Toggle.
								$sidebar.toggleClass('inactive');

						});

				}

			// Events.

				// Link clicks.
					$sidebar.on('click', 'a', function(event) {

						// >large? Bail.
							if (!skel.breakpoint('large').active)
								return;

						// Vars.
							var $a = $(this),
								href = $a.attr('href'),
								target = $a.attr('target');

						// Prevent default.
							event.preventDefault();
							event.stopPropagation();

						// Check URL.
							if (!href || href == '#' || href == '')
								return;

						// Hide sidebar.
							$sidebar.addClass('inactive');

						// Redirect to href.
							setTimeout(function() {

								if (target == '_blank')
									window.open(href);
								else
									window.location.href = href;

							}, 500);

					});

				// Prevent certain events inside the panel from bubbling.
					$sidebar.on('click touchend touchstart touchmove', function(event) {

						// >large? Bail.
							if (!skel.breakpoint('large').active)
								return;

						// Prevent propagation.
							event.stopPropagation();

					});

				// Hide panel on body click/tap.
					$body.on('click touchend', function(event) {

						// >large? Bail.
							if (!skel.breakpoint('large').active)
								return;

						// Deactivate.
							$sidebar.addClass('inactive');

					});
